### ISSUE TITLE
getting this error when running zsteg on a png

### ISSUE THREAD

**Issue by rosidae** [zed-0xff/zsteg#11]
```
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/file_cmd.rb:106:in `stop!': undefined method `close' for nil:NilClass (NoMethodError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/checker.rb:119:in `ensure in check'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/checker.rb:119:in `check'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:245:in `check'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:162:in `block (2 levels) in run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:158:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:158:in `block in run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each_with_index'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg.rb:30:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/bin/zsteg:8:in `<top (required)>'
        from C:/Ruby30-x64/bin/zsteg:23:in `load'
        from C:/Ruby30-x64/bin/zsteg:23:in `<main>'
C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:221:in `spawn': No such file or directory - file -n -b -f - (Errno::ENOENT)
        from C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
        from C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:102:in `popen3'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/file_cmd.rb:67:in `start!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/checker.rb:68:in `check'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:245:in `check'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:162:in `block (2 levels) in run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:158:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:158:in `block in run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each_with_index'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/lib/zsteg.rb:30:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zsteg-0.2.4/bin/zsteg:8:in `<top (required)>'
        from C:/Ruby30-x64/bin/zsteg:23:in `load'
        from C:/Ruby30-x64/bin/zsteg:23:in `<main>'
```

**Comment by Darth-Carrotpie** [comment]
Same issue. Why is it closed? How did you solve it?
Version: `C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/zsteg-0.2.13`
