### ISSUE TITLE
Files causing abnormal behavior

### ISSUE THREAD

**Issue by Rloota** [zed-0xff/zsteg#16]
Hi,

I have a couple .pngs that causes zsteg to behave abnormally.

sample1.png  
![sample1](https://user-images.githubusercontent.com/39261760/149511457-47db5096-662d-4221-84f9-1c2a0e20e323.png)
Traceback:

Traceback (most recent call last):                                                                                              16: from /usr/local/bin/zsteg:23:in `<main>'                                                                            15: from /usr/local/bin/zsteg:23:in `load'                                                                              14: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/bin/zsteg:8:in `<top (required)>'                                         13: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg.rb:30:in `run'                                                  12: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/cli/cli.rb:151:in `run'                                         11: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/cli/cli.rb:151:in `each_with_index'                             10: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/cli/cli.rb:151:in `each'                                         9: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/cli/cli.rb:158:in `block in run'                                 8: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/cli/cli.rb:158:in `each'                                         7: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/cli/cli.rb:162:in `block (2 levels) in run'                      6: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/cli/cli.rb:245:in `check'                                        5: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/checker.rb:113:in `check'                                        4: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/analyzer.rb:11:in `analyze!'                                     3: from /var/lib/gems/2.7.0/gems/zsteg-0.2.5/lib/zsteg/analyzer.rb:34:in `detect_block_size'                            2: from /var/lib/gems/2.7.0/gems/zpng-0.3.3/lib/zpng/image.rb:337:in `[]'                                               1: from /var/lib/gems/2.7.0/gems/zpng-0.3.3/lib/zpng/scan_line.rb:147:in `[]'                                  /var/lib/gems/2.7.0/gems/zpng-0.3.3/lib/zpng/scan_line.rb:289:in `decoded_bytes': invalid ScanLine filter 252 (RuntimeError)

 Additionally I have a malformed .png that a causes memory leak on my system and the analysis never finishes. If you want I can share that too via method you prefer.

Thanks for making a great tool

**Comment by zed-0xff** [comment]
Hi! Pls send all them to my email zed.0xff (at) gmail
