### ISSUE TITLE
How to extract `b10000000,r,lsb,yx` ?

### ISSUE THREAD

**Issue by wgf4242** [zed-0xff/zsteg#23]
Solved

zsteg -b 0x80 -c r -o yx mmm.png -n 0 -v
```
b10000000,r,lsb,yx  .. text: "passkey_is_xxxxx"
```

```
➜  lsbtest zsteg -e b10000000,r,lsb,yx mmm.png                              
Traceback (most recent call last):
	14: from /usr/local/bin/zsteg:23:in `<main>'
	13: from /usr/local/bin/zsteg:23:in `load'
	12: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/bin/zsteg:8:in `<top (required)>'
	11: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg.rb:30:in `run'
	10: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:151:in `run'
	 9: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:151:in `each_with_index'
	 8: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:151:in `each'
	 7: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:158:in `block in run'
	 6: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:158:in `each'
	 5: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:160:in `block (2 levels) in run'
	 4: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:249:in `extract'
	 3: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:235:in `_extract_data'
	 2: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:198:in `decode_param_string'
	 1: from /var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:198:in `each'
/var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb:215:in `block in decode_param_string': uknown param "b10000000" (RuntimeError)
```

__Solved__ 

edit `/var/lib/gems/2.6.0/gems/zsteg-0.2.11/lib/zsteg/cli/cli.rb`

```
        when /^(\d+)b$/, /^b(\d)$/
```
to
```
       when /^(\d+)b$/, /^b(\d+)$/
```

**Comment by zed-0xff** [comment]
thx! fixed.
