### ISSUE TITLE
There is a problem analyzing bmp files, how should I solve it?

### ISSUE THREAD

**Issue by xileshi** [zed-0xff/zsteg#42]
[?] 2 bytes of extra data after image end (IEND), offset = 0x269b0e
extradata:0         .. ["\x00" repeated 2 times]
imagedata           .. file: OpenPGP Public Key
b1,lsb,bY           .. /var/lib/gems/3.1.0/gems/iostruct-0.1.2/lib/iostruct.rb:136:in `block in inspect': undefined method `type' for nil:NilClass (NoMethodError)

          when f.type == Integer
                ^^^^^
        from /var/lib/gems/3.1.0/gems/iostruct-0.1.2/lib/iostruct.rb:133:in `each'
        from /var/lib/gems/3.1.0/gems/iostruct-0.1.2/lib/iostruct.rb:133:in `map'
        from /var/lib/gems/3.1.0/gems/iostruct-0.1.2/lib/iostruct.rb:133:in `inspect'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:291:in `puts'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:291:in `puts'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:291:in `show_result'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:326:in `process_result'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:271:in `check_channels'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:191:in `check_channels'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:116:in `block (3 levels) in check'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:99:in `each'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:99:in `block (2 levels) in check'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:98:in `each'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:98:in `block in check'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:97:in `each'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:97:in `check'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:258:in `check'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:172:in `block (2 levels) in run'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:168:in `each'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:168:in `block in run'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:161:in `each'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:161:in `each_with_index'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:161:in `run'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg.rb:26:in `run'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/bin/zsteg:8:in `<top (required)>'
        from /usr/local/bin/zsteg:25:in `load'
        from /usr/local/bin/zsteg:25:in `<main>'

**Comment by dk19930125** [comment]
me too。Do you solve ？

**Comment by Nahuel-Nina-07** [comment]
I have the same problem when parsing .png files
![problemZsteg](https://github.com/user-attachments/assets/13e3c7d5-9b04-43cb-b175-8e1cfb9ea030)

**Comment by zch050217** [comment]
b1,bgr,lsb,xy       .. /var/lib/gems/3.0.0/gems/iostruct-0.1.2/lib/iostruct.rb:136:in `block in inspect': undefined method `type' for nil:NilClass (NoMethodError)
        from /var/lib/gems/3.0.0/gems/iostruct-0.1.2/lib/iostruct.rb:133:in `each'
        from /var/lib/gems/3.0.0/gems/iostruct-0.1.2/lib/iostruct.rb:133:in `map'
        from /var/lib/gems/3.0.0/gems/iostruct-0.1.2/lib/iostruct.rb:133:in `inspect'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:291:in `puts'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:291:in `puts'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:291:in `show_result'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:326:in `process_result'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:271:in `check_channels'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:191:in `check_channels'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:118:in `block (4 levels) in check'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:118:in `each'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:118:in `block (3 levels) in check'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:99:in `each'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:99:in `block (2 levels) in check'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:98:in `each'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:98:in `block in check'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:97:in `each'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/checker.rb:97:in `check'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:258:in `check'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:172:in `block (2 levels) in run'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:168:in `each'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:168:in `block in run'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:161:in `each'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:161:in `each_with_index'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:161:in `run'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/lib/zsteg.rb:26:in `run'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.13/bin/zsteg:8:in `<top (required)>'
        from /usr/local/bin/zsteg:25:in `load'
        from /usr/local/bin/zsteg:25:in `<main>'


me too,how can we solve it

**Comment by echo38322** [comment]
metoo [?] 2 bytes of extra data after image end (IEND), offset = 0x269b0e
extradata:0         .. ["\x00" repeated 2 times]
imagedata           .. file: OpenPGP Public Key
b1,lsb,bY           .. /var/lib/gems/3.0.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect': stack level too deep (SystemStackError)
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.12/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.0.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.12/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.0.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.12/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.0.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.12/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.0.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect'
         ... 10906 levels...
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.12/lib/zsteg.rb:30:in `run'
        from /var/lib/gems/3.0.0/gems/zsteg-0.2.12/bin/zsteg:8:in `<top (required)>'
        from /usr/local/bin/zsteg:25:in `load'
        from /usr/local/bin/zsteg:25:in `<main>'
