### ISSUE TITLE
Error:stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by double-evil** [zed-0xff/zsteg#44]
Hello Zed.
I followed the method posted in another issue and added export **RUBY_THREAD_VM_STACK_SIZE=500000000** to the **.zshrc** file, but the error still occurred.
I used **sudo-i** command and get root privilege first.
I used **nano ~/.zshrc** to open the file and added the above command at the bottom line. I don’t know where the problem is but I still get an error.
I used the zsteg to analyse a .bmp picture and it's a CTF problem.I see other writeup uses zsteg solve the problem successfully.
Hope you can help me and Thank you very much.

**Comment by double-evil** [comment]
zsteg 1.bmp   
[?] 2 bytes of extra data after image end (IEND), offset = 0x269b0e
extradata:0         .. ["\x00" repeated 2 times]
imagedata           .. file: OpenPGP Public Key
b1,lsb,bY           .. /var/lib/gems/3.1.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect': stack level too deep (SystemStackError)
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.1.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.1.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.1.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg/checker/wbstego.rb:41:in `to_s'
        from /var/lib/gems/3.1.0/gems/iostruct-0.1.3/lib/iostruct.rb:159:in `inspect'
         ... 4807703 levels...
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/lib/zsteg.rb:26:in `run'
        from /var/lib/gems/3.1.0/gems/zsteg-0.2.13/bin/zsteg:8:in `<top (required)>'
        from /usr/local/bin/zsteg:25:in `load'
        from /usr/local/bin/zsteg:25:in `<main>'

**Comment by sunshine100128** [comment]
一模一样的问题，我也想知道该如何解决

**Comment by rain878** [comment]
me too! help

**Comment by rain1andsnow2a** [comment]
+1，help

**Comment by Daniel20001021** [comment]
Same issue help pls.
