### ISSUE TITLE
Error After Reinstallling on Kali

### ISSUE THREAD

**Issue by SharonCohenGitHub** [zed-0xff/zsteg#9]
I've just reinstalled zsteg and getting the following error:

```

└─$ sudo gem uninstall zsteg                    
[sudo] password for user: 
Remove executables:
        zsteg, zsteg-mask, zsteg-reflow

in addition to the gem? [Yn]  Y
Removing zsteg
Removing zsteg-mask
Removing zsteg-reflow
Successfully uninstalled zsteg-0.2.2

┌──(user㉿kali)-[~]
└─$ sudo gem install zsteg --force                                       1 ⨯
Fetching zsteg-0.2.2.gem
Successfully installed zsteg-0.2.2
Parsing documentation for zsteg-0.2.2
Installing ri documentation for zsteg-0.2.2
Done installing documentation for zsteg after 0 seconds
1 gem installed
                                                                             
┌──(user㉿kali)-[~]
└─$ zsteg
Traceback (most recent call last):
        10: from /usr/local/bin/zsteg:23:in `<main>'
         9: from /usr/local/bin/zsteg:23:in `load'
         8: from /var/lib/gems/2.7.0/gems/zsteg-0.2.2/bin/zsteg:6:in `<top (required)>'
         7: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
         6: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
         5: from /var/lib/gems/2.7.0/gems/zsteg-0.2.2/lib/zsteg.rb:9:in `<top (required)>'
         4: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
         3: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
         2: from /var/lib/gems/2.7.0/gems/zsteg-0.2.2/lib/zsteg/result.rb:2:in `<top (required)>'
         1: from /var/lib/gems/2.7.0/gems/zsteg-0.2.2/lib/zsteg/result.rb:3:in `<module:ZSteg>'
/var/lib/gems/2.7.0/gems/zsteg-0.2.2/lib/zsteg/result.rb:11:in `<module:Result>': uninitialized constant ZSteg::Result::IOStruct (NameError)
Did you mean?  ZSteg::Result::Struct
```

**Comment by zed-0xff** [comment]
try newer version 0.2.3

**Comment by SharonCohenGitHub** [comment]
Thank you for the reply @zed-0xff!

Still getting the same error however:
```
/var/lib/gems/2.7.0/gems/zsteg-0.2.3/lib/zsteg/result.rb:11:in `<module:Result>': uninitialized constant ZSteg::Result::IOStruct (NameError)
Did you mean?  ZSteg::Result::Struct
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.3/lib/zsteg/result.rb:3:in `<module:ZSteg>'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.3/lib/zsteg/result.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.3/lib/zsteg.rb:9:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.3/bin/zsteg:6:in `<top (required)>'
	from /usr/local/bin/zsteg:23:in `load'
	from /usr/local/bin/zsteg:23:in `<main>'
```

Distro info:
```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.4"
VERSION_ID="2020.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```

**Comment by zed-0xff** [comment]
Can you also post the exact ruby version?

**Comment by SharonCohenGitHub** [comment]
Ruby version:

```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
```

**Comment by zed-0xff** [comment]
![VirtualBox_Kali-Linux-2020 4-vbox-amd64_21_02_2021_11_17_18](https://user-images.githubusercontent.com/5986/108620687-754d7a80-7436-11eb-8435-2705112691b3.png)

I've just tried fresh Kali VirtualBox image, and it worked just fine.
btw, why you installed with `--force` flag?

Try to remove gems `iostruct` & `zsteg` and reinstall `zsteg` without `--force` flag.

**Comment by SharonCohenGitHub** [comment]
Peculiar!

Uninstalled (`iostruct` & `zsteg`) and reinstalled (`zsteg 0.24` without `--force` flag) and the following happens:

```
/var/lib/gems/2.7.0/gems/zpng-0.3.2/lib/zpng/string_ext.rb:7:in `block (2 levels) in <class:String>': undefined method `color' for #<String:0x00005618bf08ad80> (NoMethodError)
	from /var/lib/gems/2.7.0/gems/zpng-0.3.2/lib/zpng/image.rb:140:in `_from_io'
	from /var/lib/gems/2.7.0/gems/zpng-0.3.2/lib/zpng/image.rb:37:in `initialize'
	from /var/lib/gems/2.7.0/gems/zpng-0.3.2/lib/zpng/image.rb:72:in `new'
	from /var/lib/gems/2.7.0/gems/zpng-0.3.2/lib/zpng/image.rb:72:in `block in load'
	from /var/lib/gems/2.7.0/gems/zpng-0.3.2/lib/zpng/image.rb:71:in `open'
	from /var/lib/gems/2.7.0/gems/zpng-0.3.2/lib/zpng/image.rb:71:in `load'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:175:in `load_image'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:156:in `block in run'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each_with_index'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `run'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg.rb:30:in `run'
	from /var/lib/gems/2.7.0/gems/zsteg-0.2.4/bin/zsteg:8:in `<top (required)>'
	from /usr/local/bin/zsteg:23:in `load'
	from /usr/local/bin/zsteg:23:in `<main>'
```

Which `znpg` version do you use?

**Comment by zed-0xff** [comment]
I believe there's something wrong with your rubygems, can you try a clean Kali install?
```
iostruct (0.0.4)
zpng (0.3.2)
```

**Comment by SharonCohenGitHub** [comment]
Sounds about right, moved all files and started from scratch - now it works!

Thank you for your time & help!
